name: tensorflow_envs2
channels:
  - conda-forge
  - defaults
dependencies:
  - tensorflow-gpu==2.5
  - keras=2.4.3
  - imageio=2.9.0
  - python=3.8
  - scipy
  - libopencv
  - opencv
  - py-opencv
  - scikit-learn
  - pydot
  - python=3.8.8
  - python-graphviz
  - pip
  - matplotlib 
  - tqdm
  - pip:
    - patchify==0.2.3
