name: tensorflow_envs2
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.3.0
  - absl-py=0.15.0
  - aiohttp=3.8.1
  - aiosignal=1.2.0
  - alsa-lib=1.2.3.2
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=4.0.1
  - atk-1.0=2.36.0
  - attrs=21.4.0
  - blinker=1.4
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.07.19
  - cachetools=4.2.2
  - cairo=1.16.0
  - certifi=2022.6.15
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.0.4
  - cryptography=37.0.1
  - cudatoolkit=10.1.243
  - cudnn=7.6.5.32
  - cupti=10.1.168
  - cycler=0.11.0
  - dataclasses=0.8
  - dbus=1.13.18
  - expat=2.4.4
  - ffmpeg=4.3.2
  - flake8=4.0.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.25.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozenlist=1.2.0
  - gast=0.4.0
  - gdk-pixbuf=2.42.6
  - gettext=0.21.0
  - giflib=5.2.1
  - glib=2.68.4
  - glib-tools=2.68.4
  - gmp=6.2.1
  - gnutls=3.6.15
  - gobject-introspection=1.68.0
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - graphite2=1.3.14
  - graphviz=2.49.1
  - gst-plugins-base=1.18.5
  - gstreamer=1.18.5
  - gtk2=2.24.33
  - gts=0.7.6
  - harfbuzz=2.9.1
  - hdf5=1.10.6
  - icu=68.1
  - idna=3.3
  - imageio=2.9.0
  - importlib-metadata=4.11.3
  - jasper=1.900.1
  - joblib=1.1.0
  - jpeg=9e
  - keras=2.4.3
  - keras-preprocessing=1.1.2
  - keyutils=1.6.1
  - kiwisolver=1.4.2
  - krb5=1.19.2
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=11.1.0
  - libcurl=7.83.1
  - libdeflate=1.8
  - libedit=3.1.20210910
  - libev=4.33
  - libevent=2.1.10
  - libffi=3.3
  - libgcc-ng=12.1.0
  - libgd=2.3.3
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libglib=2.68.4
  - libgomp=12.1.0
  - libiconv=1.16
  - libidn2=2.3.2
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm11=11.1.0
  - libnghttp2=1.47.0
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopencv=4.5.3
  - libopus=1.3.1
  - libpng=1.6.37
  - libpq=13.5
  - libprotobuf=3.16.0
  - librsvg=2.52.2
  - libsqlite=3.39.2
  - libssh2=1.10.0
  - libstdcxx-ng=12.1.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libtool=2.4.6
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libvorbis=1.3.7
  - libwebp=1.2.2
  - libwebp-base=1.2.2
  - libxcb=1.15
  - libxkbcommon=1.0.3
  - libxml2=2.9.12
  - libzlib=1.2.12
  - lz4-c=1.9.3
  - markdown=3.3.4
  - markupsafe=2.1.1
  - matplotlib=3.5.3
  - matplotlib-base=3.5.3
  - mccabe=0.7.0
  - multidict=5.2.0
  - munkres=1.1.4
  - mypy=0.910
  - mypy_extensions=0.4.3
  - mysql-common=8.0.30
  - mysql-libs=8.0.30
  - ncurses=6.3
  - nettle=3.7.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nspr=4.33
  - nss=3.74
  - oauthlib=3.2.0
  - opencv=4.5.3
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=1.1.1q
  - opt_einsum=3.3.0
  - packaging=21.3
  - pango=1.48.10
  - pcre=8.45
  - pillow=9.2.0
  - pip=22.2.2
  - pixman=0.40.0
  - protobuf=3.16.0
  - psutil=5.9.0
  - pthread-stubs=0.4
  - py-opencv=4.5.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pydot=1.4.2
  - pyjwt=2.4.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pyqt=5.12.3
  - pysocks=1.7.1
  - python=3.8.8
  - python-dateutil=2.8.2
  - python-graphviz=0.20.1
  - python_abi=3.8
  - pyu2f=0.1.5
  - pyyaml=6.0
  - qt=5.12.9
  - readline=8.1.2
  - requests=2.28.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - scikit-learn=1.1.2
  - scipy=1.9.0
  - setuptools=63.4.1
  - sqlite=3.39.2
  - tensorboard=2.9.0
  - tensorboard-data-server=0.6.0
  - tensorboard-plugin-wit=1.8.1
  - tensorflow=2.4.1
  - tensorflow-base=2.4.1
  - termcolor=1.1.0
  - threadpoolctl=2.2.0
  - tk=8.6.12
  - toml=0.10.2
  - tornado=6.2
  - tqdm=4.64.0
  - unicodedata2=14.0.0
  - urllib3=1.26.11
  - werkzeug=2.0.3
  - wheel=0.37.1
  - x264=1!161.3030
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.7.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.8.1
  - zipp=3.8.0
  - zlib=1.2.12
  - zstd=1.5.2
  - pip:
    - flatbuffers==1.12
    - grpcio==1.34.1
    - h5py==3.1.0
    - keras-nightly==2.5.0.dev2021032900
    - numpy==1.19.5
    - patchify==0.2.3
    - pycodestyle==2.9.1
    - pydocstyle==6.1.1
    - pyflakes==2.5.0
    - pylama==8.4.1
    - pyqt5-sip==4.19.18
    - pyqtchart==5.12
    - pyqtwebengine==5.12.1
    - six==1.15.0
    - snowballstemmer==2.2.0
    - tensorflow-estimator==2.5.0
    - tensorflow-gpu==2.5.0
    - typing-extensions==3.7.4.3
    - wrapt==1.12.1
